#!/usr/bin/env bash
# -*- mode: sh -*-

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022



################################################################################
# CONFIGS
################################################################################

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ] ; then
    PATH="$HOME/.bin:$PATH"
fi

export EDITOR='et'
export VISUAL='et'
export PAGER='less'
export BROWSER='firefox'
export TERMCMD='termite'

#Merdas uteis em geral
export GIT_HOME="$HOME/.git"

[ -d "$HOME/dotfiles" ] && export DOTFILES="$HOME/dotfiles"

# defines de Linux distribution of the current machine. E.g. Arch
export DISTRIBUTION=""
[[ -x /usr/bin/lsb_release ]] && DISTRIBUTION="$(lsb_release --id --short)"


# ADM Related stuff
export ADM="$DOTFILES/shell/lib/ADM"
function adm() {
    . "$ADM/adm.sh" "$@"
}

adm profiles

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    bashrc="$HOME/.bashrc"
    if [ -f "$bashrc" ]; then
        # shellcheck source=/dev/null
        source "$bashrc"
    fi
fi
