#!/bin/zsh

# Only for interactive shells.
[[ -o interactive ]] || exit 0

if hash tmux 2>/dev/null; then
    # Auto-start TMUX when in SSH session.
    if [ "$SSH_CONNECTION" ] && [ -z "$TMUX" ]; then
        tmux has-session -t ssh &>/dev/null && exec tmux attach -t ssh || exec tmux new -s ssh
    fi
fi

# Function to run as sourced instead of normal executed shell script
function adm() { source "$ADM/adm.sh" "$@" ; }

# runs all setup's st_rc target
adm rc --recursive "${DOTFILES}"

# loads funcs, aliases and shell vars
rc=$DOTFILES"/shell/rc.sh"
[ -f "$rc" ] && . "$rc"

FRAMEWORK=oh-my-zsh
case "${FRAMEWORK}" in
    prezto) try_source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ;;
    oh-my-zsh) try_source  "${DOTFILES}/shell/oh-my-zshrc" ;;
esac

# Machine local confs
try_source ~/.zshrc_local

# If RC_HOOK is set, the variable will be executed as a shell command after loading of rc files.
if [ -n "$RC_HOOK" ]; then
    __hook="$RC_HOOK"
    unset RC_HOOK
    $__hook
fi

return 0
