#!/bin/zsh

# Only for interactive shells.
[[ -o interactive ]] || exit 0

# loads funcs, aliases and shell vars
rc=$DOTFILES"/shell/rc.sh"
[ -f $rc ] && source $rc


FRAMEWORK=oh-my-zsh
if [ $FRAMEWORK = prezto ];then

    # Source Prezto.
    if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
    fi

elif [ $FRAMEWORK = oh-my-zsh ];then

    # Source oh-my-zsh
    if [ -r $DOTFILES/shell/oh-my-zshrc ];then
        source $DOTFILES/shell/oh-my-zshrc
    fi
fi


# Add help command
autoload -U run-help
autoload run-help-git
autoload run-help-svn
autoload run-help-svk
alias help=run-help


# zsh options
setopt AUTO_CD EXTENDED_GLOB
unsetopt share_history
# ctrl-u does the same it did in bash.
bindkey \^U backward-kill-line


# runs all setup's st_rc target
adm rcs


# Workaround #
# Make zsh autocomplete respect dircolors.
# https://github.com/robbyrussell/oh-my-zsh/issues/1563
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Machine local confs
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

# ranger Synchronize path
[ -n "$RANGERCD" ] && unset RANGERCD && ranger-cd

return 0
