#!/bin/zsh

if [ -n "$ZSH" ]; then
    echo "Oh-my-zsh already installed."
    . "$ZSH/tools/upgrade.sh"
else
    echo "Cloning oh-my-zsh."
    git clone git://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"
    ZSH="$HOME/.oh-my-zsh"
fi

echo "Creating symlinks"
ln --symbolic --force "$HOME/dotfiles/oh-my-zsh-custom/themes" "$ZSH/custom/themes"

for custom_plugin in $(ls $HOME/dotfiles/oh-my-zsh-custom/plugins/); do
    ln --symbolic --force "$HOME/dotfiles/oh-my-zsh-custom/plugins/$custom_plugin" "$ZSH/custom/plugins/$custom_plugin"
done

echo "Oh-my-zsh is ready to use."
