#!/bin/sh

################################################################################
# VARS
################################################################################
default_session="awesome"

userresources=$HOME/.Xresources
userLocalResources=$HOME/.Xresources_local
usermodmap=$HOME/.Xmodmap
xbindkeysrc=$HOME/.xbindkeysrc
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap


################################################################################
# Set keyboard as us-international with dead keys
################################################################################

setxkbmap -layout us -variant altgr-intl
setxkbmap -option keypad:pointerkeys

################################################################################
# merge in defaults and keymaps
################################################################################

[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$xbindkeysrc" ] && hash xbindkeys &>/dev/null && xbindkeys
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$userLocalResources" ] && xrdb -merge "$userLocalResources"


################################################################################
# start some nice programs
################################################################################

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi


################################################################################
# Custom settings and configs
################################################################################

# activate numlock
numlockx &

# The typematic delay indicates the amount of time (typically in miliseconds) a
# key needs to be pressed in order for the repeating process to begin. After the
# repeating process has been triggered, the character will be repeated with a
# certain frequency (usually given in Hz) specified by the typematic rate. The
# typematic delay in the virtual console is not affected by these settings.

# xset r rate <delay> <rate>
xset r rate 200 45

screen_config=~/.screenlayout/default.sh
[ -f "${screen_config}" ] && "${screen_config}"

[ -f "$HOME/.xinitrc_local" ] && . "$HOME/.xinitrc_local"

################################################################################
# start the session
################################################################################

# Here the default is the test twm and xterm of the original xinitrc
# the first arg given to startx is in $2, $1 is always xterm
session="$2"

[ -z "$session" ] && session=$default_session

echo "$session" > /tmp/session.var
echo "$@" >> /tmp/session.var

case "$session" in
	  twm		            )
		    twm &
		    #xclock -geometry 50x50-1+1 &
		    xterm -geometry 80x50+494+51 &
		    xterm -geometry 80x20+494-0 &
		    exec xterm -geometry 80x66+0+0 -name login
		    ;;
    awesome           )
        unset LUA_PATH
        unset LUA_CPATH
        exec awesome;;
    bspwm             ) exec bspwm;;
    catwm             ) exec catwm;;
    cinnamon          ) exec cinnamon-session;;
    dwm               ) exec dwm;;
    enlightenment     ) exec enlightenment_start;;
    ede               ) exec startede;;
    fluxbox           ) exec startfluxbox;;
    gnome             ) exec gnome-session;;
    gnome-classic     ) exec gnome-session --session=gnome-classic;;
    i3|i3wm           ) exec i3;;
    icewm             ) exec icewm-session;;
    jwm               ) exec jwm;;
    #kde               ) exec startkde;;
    kde               ) exec startplasma-x11;;
    mate              ) exec mate-session;;
    monster|monsterwm ) exec monsterwm;;
    notion            ) exec notion;;
    openbox           ) exec openbox-session;;
    unity             ) exec unity;;
    xfce|xfce4        ) exec startxfce4;;
    xmonad            ) exec xmonad;;

	  # When all else fails...
	  *		) exec "$session" ;;
esac
