#!/usr/bin/env python3

import os
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Iterable, Tuple

import cfscrape
from bs4 import BeautifulSoup
from feedgenerator import DefaultFeed

# from feedgen.feed

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))


def feed() -> DefaultFeed:
    return DefaultFeed(
        title='mangakakalot - Boarding School Juliet',
        link='https://mangakakalot.com/manga/kishuku_gakkou_no_juliet',
        description=
        'Simple feed via scrapping for manga mangakakalot Boarding School Juliet',
        logo=
        'https://avt.mkklcdnv3.com/avatar_225/16547-kishuku_gakkou_no_juliet.jpg',
        # fg.subtitle('This is a cool feed!')
        # fg.link( href='http://larskiesow.de/test.atom', rel='self' )
        language='en',
    )


def add_entries(fg: DefaultFeed, entries: Iterable[Tuple[str, str]]) -> None:
    for e in entries:
        fg.add_item(
            title=e[0],
            link=e[1],
            description='',
            pubdate=None,
        )


def feed_fetch(url) -> str:
    print(f'Fetching {url}')

    scrape = cfscrape.create_scraper()
    html = scrape.get(url).content
    soup = BeautifulSoup(html, features='lxml')

    # print([tag for tag in soup.findAll('div', class_="chapter-list")])
    chapter_list = soup.find('div', class_="chapter-list").findAll('a')

    fg = feed()
    add_entries(fg, ((c.contents[0], c['href']) for c in chapter_list))

    return fg.writeString("iso-8859-1")


class RSSHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        manga = self.path
        url = f'https://mangakakalot.com/manga{manga}'
        response = feed_fetch(url)

        self.send_response(200)
        self.send_header("Content-type", "text/xml")
        self.end_headers()
        self.wfile.write(response.encode('utf-8'))


def main():
    server_address = ('127.0.0.1', 9001)
    httpd = HTTPServer(server_address, RSSHandler)
    httpd.serve_forever()


if __name__ == "__main__":
    main()
